[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/:year/:month/:date/:slug/"
  to = "/blog/:year-:month-:day-:slug/"
  status = 301
  force = false