[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "http://ericdfields.com/:year/:month/:date/:slug/"
  to = "https://ericbrookfield.com/blog/:year-:month-:date-:slug/"
  status = 301
  force = false
[[redirects]]
  from = "http://ericdfields.com"
  to = "https://ericbrookfield.com"
  status = 301
  force = false